SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
UNLOCK TABLES;

DROP TABLE IF EXISTS `stores`;

-- Stores Schema
CREATE TABLE IF NOT EXISTS `stores` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `businessTypeId` INTEGER UNSIGNED,
  `userId` BIGINT UNSIGNED NULL DEFAULT NULL,
  `storePicture` varchar(255) NULL,
  `lat` FLOAT(11, 7) NULL,
  `lan` FLOAT(11, 7) NULL,
  `storeCode` varchar(50) NULL,
  `status` varchar(10) DEFAULT 'INACTIVE',
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createdBy` BIGINT UNSIGNED,
  `updatedBy` BIGINT UNSIGNED,
  PRIMARY KEY (`id`),
  INDEX `uq_store_name` (`name` ASC)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=100 ;

